import type { Metadata } from 'next';
import './globals.css';
import QueryProvider from '@/domains/common/providers/QueryProvider';

export const metadata: Metadata = {
  title: 'CHERRY',
  description: 'Generated by create next app',
  icons: {
    icon: '/icons/Logo.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css"
        />
      </head>
      <body className="antialiased bg-Fill-95">
        <div className="layout-container-no-padding bg-Static-White">
          <QueryProvider>{children}</QueryProvider>
        </div>
      </body>
    </html>
  );
}
