import type { Metadata } from 'next';
import './globals.css';
import QueryProvider from '@/domains/common/providers/QueryProvider';

export const metadata: Metadata = {
  title: 'CHERRY',
  description: 'Generated by create next app',
  icons: {
    icon: '/Logo.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <header></header>
        <div className="layout-container">
          <QueryProvider>{children}</QueryProvider>
        </div>
      </body>
    </html>
  );
}
