import type { Brand, Product } from '../types/ProductsType';

export const mockBrands: Brand[] = [
  { id: 'b1', name: 'Brand A' },
  { id: 'b2', name: 'Brand B' },
  { id: 'b3', name: 'Brand C' },
  { id: 'b4', name: 'Brand D' },
  { id: 'b5', name: 'Brand E' },
  { id: 'b6', name: 'Brand F' },
  { id: 'b7', name: 'Brand G' },
  { id: 'b8', name: 'Brand H' },
  { id: 'b9', name: 'Brand I' },
];

export const mockProducts: Product[] = [
  {
    id: 'p1',
    brandId: 'b1',
    brandName: 'Brand A',
    title: 'Noise-Canceling Headset',
    pricePerDay: 9000,
    imageUrl: 'https://placehold.co/360x240',
    reservable: true,
  },
  {
    id: 'p2',
    brandId: 'b1',
    brandName: 'Brand A',
    title: 'Streaming Webcam',
    pricePerDay: 12000,
    imageUrl: 'https://placehold.co/360x240',
    reservable: true,
  },
  {
    id: 'p3',
    brandId: 'b2',
    brandName: 'Brand B',
    title: '4K Action Camera',
    pricePerDay: 18000,
    imageUrl: 'https://placehold.co/360x240',
    reservable: true,
  },
  {
    id: 'p4',
    brandId: 'b3',
    brandName: 'Brand C',
    title: 'Studio Mic',
    pricePerDay: 7000,
    imageUrl: 'https://placehold.co/360x240',
    reservable: true,
  },
  {
    id: 'p5',
    brandId: 'b1',
    brandName: 'Brand A',
    title: 'Portable Light',
    pricePerDay: 5000,
    imageUrl: 'https://placehold.co/360x240',
    reservable: true,
  },
  {
    id: 'p6',
    brandId: 'b1',
    brandName: 'Brand A',
    title: 'Portable Light',
    pricePerDay: 5000,
    imageUrl: 'https://placehold.co/360x240',
    reservable: true,
  },
  {
    id: 'p7',
    brandId: 'b1',
    brandName: 'Brand A',
    title: 'Portable Light',
    pricePerDay: 5000,
    imageUrl: 'https://placehold.co/360x240',
    reservable: true,
  },
  {
    id: 'p8',
    brandId: 'b1',
    brandName: 'Brand A',
    title: 'Portable Light',
    pricePerDay: 5000,
    imageUrl: 'https://placehold.co/360x240',
    reservable: true,
  },
  {
    id: 'p9',
    brandId: 'b1',
    brandName: 'Brand A',
    title: 'Portable Light',
    pricePerDay: 5000,
    imageUrl: 'https://placehold.co/360x240',
    reservable: true,
  },
  {
    id: 'p10',
    brandId: 'b1',
    brandName: 'Brand A',
    title: 'Portable Light',
    pricePerDay: 5000,
    imageUrl: 'https://placehold.co/360x240',
    reservable: true,
  },
];
